/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.figuras_geometricas.GUI_Figuras;

import com.mycompany.figuras_geometricas.Circulo;
import com.mycompany.figuras_geometricas.Cuadrado;
import com.mycompany.figuras_geometricas.Otro_Triangulo;
import com.mycompany.figuras_geometricas.Triangulo_equilatero;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author hp
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        ocultar_Panel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_figuras = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        rb_cuadrado = new javax.swing.JRadioButton();
        rb_circulo = new javax.swing.JRadioButton();
        rb_triangulo_equilatero = new javax.swing.JRadioButton();
        rb_otro_triangulo = new javax.swing.JRadioButton();
        jp_circulo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txt_lado_circulo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        calcular_circulo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_area = new javax.swing.JLabel();
        lbl_perimetro = new javax.swing.JLabel();
        jp_cuadrado = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_lado_cuadrado = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        calcular_cuadrado = new javax.swing.JButton();
        jp_triangulo_equilatero = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_altura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        calcular_triangulo = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txt_base = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jp_otro_triangulo = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_lado1_triangulo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        calcular_otro_triangulo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_otro_triangulo_base = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txt_lado2_triangulo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txt_otro_triangulo_altura = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("FORMULARIO FIGURAS");

        jComboBox1.setBackground(new java.awt.Color(102, 0, 0));
        jComboBox1.setForeground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CUADRADO", "CIRCULO", "TRIANGULO EQUILATERO", "OTRO TRIANGULO" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        group_figuras.add(rb_cuadrado);
        rb_cuadrado.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        rb_cuadrado.setLabel("CUADRADO");
        rb_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_cuadradoActionPerformed(evt);
            }
        });

        group_figuras.add(rb_circulo);
        rb_circulo.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        rb_circulo.setLabel("CIRCULO");
        rb_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_circuloActionPerformed(evt);
            }
        });

        group_figuras.add(rb_triangulo_equilatero);
        rb_triangulo_equilatero.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        rb_triangulo_equilatero.setLabel("TRIANGULO EQUILATERO");
        rb_triangulo_equilatero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_triangulo_equilateroActionPerformed(evt);
            }
        });

        group_figuras.add(rb_otro_triangulo);
        rb_otro_triangulo.setFont(new java.awt.Font("Comic Sans MS", 0, 10)); // NOI18N
        rb_otro_triangulo.setLabel("OTRO TRIANGULO");
        rb_otro_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_otro_trianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_circulo)
                            .addComponent(rb_cuadrado)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_otro_triangulo)
                            .addComponent(rb_triangulo_equilatero))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(rb_cuadrado))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_circulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_triangulo_equilatero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb_otro_triangulo)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jp_circulo.setBackground(new java.awt.Color(0, 102, 102));
        jp_circulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CIRCULO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel2.setText("INGRESE EL VALOR DEL RADIO:");

        txt_lado_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lado_circuloActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel3.setText("CM");

        calcular_circulo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        calcular_circulo.setText("CALCULAR");
        calcular_circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_circuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_circuloLayout = new javax.swing.GroupLayout(jp_circulo);
        jp_circulo.setLayout(jp_circuloLayout);
        jp_circuloLayout.setHorizontalGroup(
            jp_circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_circuloLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_lado_circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcular_circulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_circuloLayout.setVerticalGroup(
            jp_circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_circuloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_circuloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_lado_circulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(calcular_circulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "RESULTADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        lbl_area.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbl_area.setText("EL ÁREA ES:");

        lbl_perimetro.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        lbl_perimetro.setText("EL PERIMETRO ES:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_area)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_perimetro)
                .addGap(164, 164, 164))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_area)
                .addComponent(lbl_perimetro))
        );

        jp_cuadrado.setBackground(new java.awt.Color(255, 51, 51));
        jp_cuadrado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CUADRADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setText("INGRESE EL VALOR DEL LADO:");

        txt_lado_cuadrado.setEditable(false);
        txt_lado_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lado_cuadradoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel7.setText("CM");

        calcular_cuadrado.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        calcular_cuadrado.setText("CALCULAR");
        calcular_cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_cuadradoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jp_cuadradoLayout = new javax.swing.GroupLayout(jp_cuadrado);
        jp_cuadrado.setLayout(jp_cuadradoLayout);
        jp_cuadradoLayout.setHorizontalGroup(
            jp_cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cuadradoLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_lado_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(calcular_cuadrado)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jp_cuadradoLayout.setVerticalGroup(
            jp_cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_cuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_cuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_lado_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(calcular_cuadrado))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jp_triangulo_equilatero.setBackground(new java.awt.Color(51, 102, 0));
        jp_triangulo_equilatero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TRIANGULO EQUILATERO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel8.setText("INGRESE EL VALOR DE LA BASE:");

        txt_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alturaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel9.setText("CM");

        calcular_triangulo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        calcular_triangulo.setText("CALCULAR");
        calcular_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_trianguloActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel16.setText("INGRESE EL VALOR DE LA ALTURA:");

        txt_base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_baseActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel17.setText("CM");

        javax.swing.GroupLayout jp_triangulo_equilateroLayout = new javax.swing.GroupLayout(jp_triangulo_equilatero);
        jp_triangulo_equilatero.setLayout(jp_triangulo_equilateroLayout);
        jp_triangulo_equilateroLayout.setHorizontalGroup(
            jp_triangulo_equilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_triangulo_equilateroLayout.createSequentialGroup()
                .addGroup(jp_triangulo_equilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jp_triangulo_equilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_triangulo_equilateroLayout.createSequentialGroup()
                        .addComponent(txt_base, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addGroup(jp_triangulo_equilateroLayout.createSequentialGroup()
                        .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(calcular_triangulo)
                .addContainerGap())
        );
        jp_triangulo_equilateroLayout.setVerticalGroup(
            jp_triangulo_equilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_triangulo_equilateroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_triangulo_equilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(calcular_triangulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jp_triangulo_equilateroLayout.createSequentialGroup()
                        .addGroup(jp_triangulo_equilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(txt_base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_triangulo_equilateroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txt_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jp_otro_triangulo.setBackground(new java.awt.Color(255, 102, 0));
        jp_otro_triangulo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OTRO TRIANGULO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 12))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel10.setText("INGRESE EL VALOR DEL LADO 1:");

        txt_lado1_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lado1_trianguloActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel11.setText("CM");

        calcular_otro_triangulo.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        calcular_otro_triangulo.setText("CALCULAR");
        calcular_otro_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_otro_trianguloActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel12.setText("INGRESE EL VALOR DEL LADO 2:");

        txt_otro_triangulo_base.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otro_triangulo_baseActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel13.setText("CM");

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel14.setText("INGRESE EL VALOR DE LA BASE:");

        txt_lado2_triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_lado2_trianguloActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel15.setText("CM");

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel18.setText("INGRESE EL VALOR DE LA ALTURA:");

        txt_otro_triangulo_altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_otro_triangulo_alturaActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel19.setText("CM");

        javax.swing.GroupLayout jp_otro_trianguloLayout = new javax.swing.GroupLayout(jp_otro_triangulo);
        jp_otro_triangulo.setLayout(jp_otro_trianguloLayout);
        jp_otro_trianguloLayout.setHorizontalGroup(
            jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_lado1_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11))
                    .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                        .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                                .addComponent(txt_otro_triangulo_altura, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19))
                            .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                                .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                                        .addComponent(txt_lado2_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                                        .addComponent(txt_otro_triangulo_base, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15)))
                                .addGap(28, 28, 28)
                                .addComponent(calcular_otro_triangulo)))))
                .addContainerGap())
        );
        jp_otro_trianguloLayout.setVerticalGroup(
            jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_lado1_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_otro_trianguloLayout.createSequentialGroup()
                        .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(txt_lado2_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txt_otro_triangulo_base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addComponent(calcular_otro_triangulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addGroup(jp_otro_trianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_otro_triangulo_altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(51, 204, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 51));

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jToggleButton1)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jToggleButton1)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_cuadrado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_circulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jp_triangulo_equilatero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(195, 195, 195))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jp_otro_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jp_cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jp_circulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_triangulo_equilatero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jp_otro_triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void rb_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_cuadradoActionPerformed
        jp_cuadrado.setVisible(true);
        jp_circulo.setVisible(false);
        jp_triangulo_equilatero.setVisible(false);
        jp_otro_triangulo.setVisible(false);
    }//GEN-LAST:event_rb_cuadradoActionPerformed

    private void rb_otro_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_otro_trianguloActionPerformed
        jp_cuadrado.setVisible(false);
        jp_circulo.setVisible(false);
        jp_triangulo_equilatero.setVisible(false);
        jp_otro_triangulo.setVisible(true);
    }//GEN-LAST:event_rb_otro_trianguloActionPerformed

    private void rb_triangulo_equilateroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_triangulo_equilateroActionPerformed
        jp_cuadrado.setVisible(false);
        jp_circulo.setVisible(false);
        jp_triangulo_equilatero.setVisible(true);
        jp_otro_triangulo.setVisible(false);
    }//GEN-LAST:event_rb_triangulo_equilateroActionPerformed

    private void rb_circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_circuloActionPerformed
        jp_cuadrado.setVisible(false);
        jp_circulo.setVisible(true);
        jp_triangulo_equilatero.setVisible(false);
        jp_otro_triangulo.setVisible(false);
    }//GEN-LAST:event_rb_circuloActionPerformed

    private void calcular_otro_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_otro_trianguloActionPerformed
        double calc_lado1 = Double.parseDouble(txt_lado1_triangulo.getText());
        double calc_lado2 = Double.parseDouble(txt_lado2_triangulo.getText());
        double calc_otro_triangulo_base = Double.parseDouble(txt_otro_triangulo_base.getText());
        double calc_otro_triangulo_altura = Double.parseDouble(txt_otro_triangulo_altura.getText());
        Otro_Triangulo objOtroTriangulo =
                new Otro_Triangulo(calc_lado1, calc_lado2, calc_otro_triangulo_base , calc_otro_triangulo_altura, "Otro Triangulo");
        objOtroTriangulo.setArea_figura();
        objOtroTriangulo.setPerimetro();
        lbl_area.setText("El área es:" + objOtroTriangulo.getArea_figura());
        lbl_perimetro.setText("El perimetro es:" + objOtroTriangulo.getPerimetro());
        
    }//GEN-LAST:event_calcular_otro_trianguloActionPerformed

    private void txt_lado2_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lado2_trianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lado2_trianguloActionPerformed

    private void txt_lado1_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lado1_trianguloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lado1_trianguloActionPerformed

    private void calcular_circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_circuloActionPerformed
        double calc_circulo = Double.parseDouble(txt_lado_circulo.getText());
        Circulo objcirculo = new Circulo(calc_circulo,"Círculo");
        objcirculo.setArea_figura();
        objcirculo.setPerimetro();
        lbl_area.setText("El área es:" + objcirculo.getArea_figura());
        lbl_perimetro.setText("El perimetro es:" + objcirculo.getPerimetro());
    }//GEN-LAST:event_calcular_circuloActionPerformed

    private void txt_lado_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lado_cuadradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lado_cuadradoActionPerformed

    private void txt_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alturaActionPerformed

    private void txt_otro_triangulo_baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otro_triangulo_baseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otro_triangulo_baseActionPerformed

    private void calcular_cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_cuadradoActionPerformed
        double calc_lado_cuadrado = Double.parseDouble(txt_lado_cuadrado.getText());
        Cuadrado objcuadrado = new Cuadrado(calc_lado_cuadrado,"Cuadrado");
        objcuadrado.setArea_figura();
        objcuadrado.setPerimetro();
        lbl_area.setText("El área es:" + objcuadrado.getArea_figura());
        lbl_perimetro.setText("El perimetro es:" + objcuadrado.getPerimetro());
    }//GEN-LAST:event_calcular_cuadradoActionPerformed

    private void txt_lado_circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_lado_circuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_lado_circuloActionPerformed

    private void calcular_trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_trianguloActionPerformed
        double calc_base = Double.parseDouble(txt_base.getText());
        double calc_altura = Double.parseDouble(txt_altura.getText());
        Triangulo_equilatero objequilatero = 
                new Triangulo_equilatero(calc_base,calc_altura,"Triángulo Equilatero");
        objequilatero.setArea_figura();
        objequilatero.setPerimetro();
        lbl_area.setText("El área es:" + objequilatero.getArea_figura());
        lbl_perimetro.setText("El perimetro es:" + objequilatero.getPerimetro());
        
    }//GEN-LAST:event_calcular_trianguloActionPerformed

    private void txt_baseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_baseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_baseActionPerformed

    private void txt_otro_triangulo_alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_otro_triangulo_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_otro_triangulo_alturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton calcular_circulo;
    private javax.swing.JButton calcular_cuadrado;
    private javax.swing.JButton calcular_otro_triangulo;
    private javax.swing.JButton calcular_triangulo;
    private javax.swing.ButtonGroup group_figuras;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel jp_circulo;
    private javax.swing.JPanel jp_cuadrado;
    private javax.swing.JPanel jp_otro_triangulo;
    private javax.swing.JPanel jp_triangulo_equilatero;
    private javax.swing.JLabel lbl_area;
    private javax.swing.JLabel lbl_perimetro;
    private javax.swing.JRadioButton rb_circulo;
    private javax.swing.JRadioButton rb_cuadrado;
    private javax.swing.JRadioButton rb_otro_triangulo;
    private javax.swing.JRadioButton rb_triangulo_equilatero;
    private javax.swing.JTextField txt_altura;
    private javax.swing.JTextField txt_base;
    private javax.swing.JTextField txt_lado1_triangulo;
    private javax.swing.JTextField txt_lado2_triangulo;
    private javax.swing.JTextField txt_lado_circulo;
    private javax.swing.JTextField txt_lado_cuadrado;
    private javax.swing.JTextField txt_otro_triangulo_altura;
    private javax.swing.JTextField txt_otro_triangulo_base;
    // End of variables declaration//GEN-END:variables

    private void ocultar_Panel() {
        jp_cuadrado.setVisible(false);
        jp_circulo.setVisible(false);
        jp_triangulo_equilatero.setVisible(false);
        jp_otro_triangulo.setVisible(false);
    }
}
